base: &base
  adapter: mysql
  host: 127.0.0.1
  username: radiant
  password: 

development:
  database: radiant_development
  <<: *base

test:
  database: radiant_test
  <<: *base

production:
  database: radiant_production
  <<: *base
