base: &base
  adapter: mysql
  host: 127.0.0.1
  username: radiant_multisite
  password: 

development:
  database: radiant_multisite_development
  <<: *base

test:
  database: radiant_multisite_test
  <<: *base

staging:
  database: radiant_multisite_staging
  <<: *base
    
production:
  database: radiant_multisite_production
  <<: *base
