---
- name: admin_breadcrumbs
  hub: netzpirat
  remotes:
    - saturnflyer
- name: application_theme
  hub: saturnflyer
  remotes:
- name: blog
  hub: netzpirat
  remotes:
    - saturnflyer
- name: change_author
  hub: saturnflyer
  remotes:
- name: conditional_tags
  hub: netzpirat
  remotes:
    - SwankInnovations
- name: copy_move
  hub: netzpirat
  remotes:
    - pilu
- name: dashboard
  hub: netzpirat
  remotes:
    - saturnflyer
- name: dav
  hub: netzpirat
  remotes:
    - willcodeforfoo
- name: gallery
  hub: netzpirat
  remotes:
    - pilu
- name: gallery_multisite
  hub: netzpirat
  remotes:
- name: help
  hub: netzpirat
  remotes:
    - saturnflyer
- name: import_export
  hub: netzpirat
  remotes:
    - radiant
- name: index_page
  hub: netzpirat
  remotes:
    - jomz
- name: multi_site
  hub: netzpirat
  remotes:
    - spanner
- name: navigation_tags
  hub: netzpirat
  remotes:
    - derencius
- name: page_preview
  hub: netzpirat
  remotes:
    - vigetlabs
    - saturnflyer
    - whistlerbrk
- name: paginate
  hub: netzpirat
  remotes:
    - saturnflyer
- name: paperclipped
  hub: netzpirat
  remotes:
    - Aissac
    - spanner
- name: paperclipped_multisite
  hub: netzpirat
  remotes:
- name: ray
  hub: netzpirat
  remotes:
    - johnmuhl
- name: scoped_admin
  hub: netzpirat
  remotes:
    - spanner
- name: search
  hub: netzpirat
  remotes:
    - radiant
- name: search_multi_site
  hub: netzpirat
  remotes:
    - RSpace
- name: seo_help
  hub: saturnflyer
  remotes:
- name: settings
  hub: netzpirat
  remotes:
    - Squeegy
- name: share_layouts
  hub: netzpirat
  remotes:
    - radiant
- name: sibling_tags
  hub: nelstrom
  remotes:
- name: site_watcher
  hub: netzpirat
  remotes:
    - saturnflyer
- name: sns
  hub: netzpirat
  remotes:
    - SwankInnovations
    - trejkaz
    - MrGossett
    - eostrom
- name: sns_minifier
  hub: netzpirat
  remotes:
    - patrickberkeley
- name: sns_multisite
  hub: netzpirat
  remotes:
- name: sns_sass_filter
  hub: netzpirat
  remotes:
- name: wym_editor_filter
  hub: netzpirat
  remotes:
    - jomz
