- name: blog
  hub: netzpirat
  remote: saturnflyer/radiant-blog-extension
- name: comments
  hub: netzpirat
  remote: ntalbott/radiant-comments 
- name: rbac
  hub: netzpirat
  remote: saturnflyer/radiant-rbac-base-extension

