---
- name: admin-breadcrumbs
  hub: netzpirat
  remote: saturnflyer/radiant-admin_breadcrumbs-extension
- name: wym-editor-filter
  hub: netzpirat
  remote: radiant-wym-editor-filter-extension
- name: copy-move
  hub: netzpirat
  remote: pilu/radiant-copy-move