---
- name: paperclipped
  hub: netzpirat
  rake: assets
  remote: kbingman/paperclipped
- name: paperclipped-multisite
  hub: netzpirat
  remote: kbingman/radiant-paperclipped_multisite-extension
- name: admin-breadcrumbs
  hub: netzpirat
  remote: saturnflyer/radiant-admin_breadcrumbs-extension
- name: wym-editor-filter
  hub: netzpirat
  remote: radiant-wym-editor-filter-extension
- name: copy-move
  hub: netzpirat
  remote: pilu/radiant-copy-move
- name: page-preview
  hub: netzpirat
  remote: vigetlabs/radiant_page_preview_extension
- name: import-export
  hub: netzpirat
  remote: radiant/radiant-import-export-extension
- name: first-reorder
  hub: jomz
- name: multi-site
  hub: netzpirat
  remote: radiant/radiant-multi-site-extension
- name: settings
  hub: netzpirat
  remote: Squeegy/radiant-settings
- name: dashboard
  hub: netzpirat
  remote: saturnflyer/radiant-dashboard-extension
- name: navigation-tags
  hub: netzpirat
  remote: derencius/navigation_tags
- name: share-layouts
  hub: netzpirat
  remote: radiant/radiant-share-layouts-extension
- name: tags
  hub: netzpirat
  remote: jomz/radiant-tags-extension
- name: tags-multi-site
  hub: netzpirat
  remote: RSpace/radiant-tags_multi_site-extension
- name: gallery
  hub: netzpirat
  remote: pilu/radiant-gallery 
- name: iphone
  hub: netzpirat
  remote: pilu/radiant-iphone-extension
- name: help
  hub: netzpirat
  remote: radiant-upload-manager-extension
- name: sns
  hub: netzpirat
  remote: SwankInnovations/radiant-sns-extension
- name: search
  hub: netzpirat
  remote: radiant/radiant-search-extension
- name: search-multi-site
  hub: netzpirat
  remote: RSpace/radiant-search_multi_site-extension
