- name: blog
  hub: netzpirat
  remote: saturnflyer/radiant-blog-extension
- name: comments
  hub: netzpirat
  remote: ntalbott/radiant-comments 
- name: copy-move
  hub: netzpirat
  remote: pilu/radiant-copy-move
- name: dashboard
  hub: netzpirat
  remote: saturnflyer/radiant-dashboard-extension
- name: gallery
  hub: netzpirat
  remote: pilu/radiant-gallery 
- name: import-export
  hub: netzpirat
  remote: radiant/radiant-import-export-extension
- name: iphone
  hub: netzpirat
  remote: pilu/radiant-iphone-extension
- name: multi-site
  hub: netzpirat
  remote: radiant/radiant-multi-site-extension
- name: navigation-tags
  hub: netzpirat
  remote: derencius/navigation_tags
- name: page-list-view
  hub: netzpirat
  remote: avonderluft/radiant-page_list_view-extension
- name: page-preview
  hub: netzpirat
  remote: vigetlabs/radiant_page_preview_extension
- name: paperclipped
  hub: netzpirat
  rake: assets
  remote: kbingman/paperclipped
- name: paperclipped-multisite
  hub: netzpirat
  remote: kbingman/radiant-paperclipped_multisite-extension
- name: rbac
  hub: netzpirat
  remote: saturnflyer/radiant-rbac-base-extension
- name: reorder
  hub: netzpirat
  remote: radiant/radiant-reorder-extension
- name: settings
  hub: netzpirat
  remote: Squeegy/radiant-settings
- name: share-layouts
  hub: netzpirat
  remote: radiant/radiant-share-layouts-extension
- name: tags
  hub: netzpirat
  remote: jomz/radiant-tags-extension
- name: templates
  hub: netzpirat
  remote: seancribbs/radiant-templates-extension
- name: upload-manager
  hub: netzpirat
  remote: radiant-upload-manager-extension
