---
- name: admin_breadcrumbs
  hub: netzpirat
- name: blog
  hub: netzpirat
- name: conditional_tags
  hub: netzpirat
- name: copy_move
  hub: netzpirat
- name: dashboard
  hub: netzpirat
- name: dav
  hub: netzpirat
- name: drag_order
  hub: netzpirat
- name: gallery
  hub: netzpirat
- name: help
  hub: netzpirat
- name: import_export
  hub: netzpirat
- name: index_page
  hub: netzpirat
- name: multi_site
  hub: netzpirat
- name: navigation_tags
  hub: netzpirat
- name: page_preview
  hub: netzpirat
- name: paperclipped
  hub: netzpirat
- name: paperclipped_multisite
  hub: netzpirat
- name: ray
  hub: netzpirat
- name: scoped_admin
  hub: netzpirat
- name: search
  hub: netzpirat
- name: search_multi_site
  hub: netzpirat
- name: settings
  hub: netzpirat
- name: share_layouts
  hub: netzpirat
- name: sns
  hub: netzpirat
- name: tags
  hub: netzpirat
- name: tags_multi_site
  hub: netzpirat
- name: wym_editor_filter
  hub: netzpirat
