---
- name: admin-breadcrumbs
  hub: netzpirat
  remote: saturnflyer/radiant-admin_breadcrumbs-extension
- name: wym-editor-filter
  hub: netzpirat
  remote: radiant-wym-editor-filter-extension
- name: copy-move
  hub: netzpirat
  remote: pilu/radiant-copy-move
- name: page-preview
  hub: netzpirat
  remote: vigetlabs/radiant_page_preview_extension
- name: import-export
  hub: netzpirat
  remote: radiant/radiant-import-export-extension
- name: reorder
  hub: netzpirat
  remote: radiant/radiant-reorder-extension
- name: multi-site
  hub: netzpirat
  remote: radiant/radiant-multi-site-extension