- name: blog
  hub: netzpirat
  remote: saturnflyer/radiant-blog-extension
- name: comments
  hub: netzpirat
  remote: ntalbott/radiant-comments 

- name: gallery
  hub: netzpirat
  remote: pilu/radiant-gallery 
- name: iphone
  hub: netzpirat
  remote: pilu/radiant-iphone-extension

- name: paperclipped
  hub: netzpirat
  rake: assets
  remote: kbingman/paperclipped
- name: paperclipped-multisite
  hub: netzpirat
  remote: kbingman/radiant-paperclipped_multisite-extension
- name: upload-manager
  hub: netzpirat
  remote: haitham/radiant-upload-manager

- name: help
  hub: netzpirat
  remote: radiant-upload-manager-extension


