#!/usr/bin/env ruby
puts "Bundle gems for Snow Leopard"
ENV["ARCHFLAGS"] = '-arch x86_64'
$LOAD_PATH.unshift File.expand_path(File.join(File.dirname(__FILE__), "..", "gems/bundler/lib"))
require 'rubygems'
require 'rubygems/command'
require 'bundler'
require 'bundler/commands/bundle_command'
Gem::Commands::BundleCommand.new.invoke(['--build-options', 'config/build/snow_leopard.yml'])
